[merger]
port = 43687
db = "postgresql://postgres:postgrespassword@host.docker.internal:5432/postgres"
redis = "rediss://connection_URI"

[telegram]
merger_url = "localhost:123"
mkey = "key"
token = "token"
chat = -11111111
